set_property IOSTANDARD LVCMOS18 [get_ports branch_outcome]
set_property IOSTANDARD LVCMOS18 [get_ports {index[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {index[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {index[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports prediction]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports {index[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports success]
set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property PACKAGE_PIN V17 [get_ports branch_outcome]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN V16 [get_ports {index[0]}]
set_property PACKAGE_PIN W16 [get_ports {index[1]}]
set_property PACKAGE_PIN W17 [get_ports {index[2]}]
set_property PACKAGE_PIN W15 [get_ports {index[3]}]
set_property PACKAGE_PIN U16 [get_ports prediction]
set_property PACKAGE_PIN R2 [get_ports reset]
set_property PACKAGE_PIN E19 [get_ports success]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
